### ISSUE TITLE
Automatic check of docstring parameters/returns based on function/class signature via pre-commit hook (pydoclint)

### ISSUE THREAD

**Issue by adamamer20** [adamamer20/mesa-frames#18]
Due to type hinting being so extensive and APIs currently being subject to substantial changes, it would be useful to have a pre-commit hook that deals with the mismatch between type hints, parameters/attribute names defined in the function/class signature and in the docstring. This would ensure that the documentation is up to date.I tried searching online but couldn't find any existing tool. However, I found a small implementation using ast in this [post](https://stackoverflow.com/a/78524959).
@rht do you know if something similar exists?

**Comment by rht** [comment]
That's a good idea. I remembered searching about this in the past, but couldn't find my past note. Anyway, searching fresh again resulted in https://github.com/jsh9/pydoclint (much faster than darglint).

```
pydoclint currently has 7 categories of style violation codes:

DOC0xx: Docstring parsing issues
DOC1xx: Violations about input arguments
DOC2xx: Violations about return argument(s)
DOC3xx: Violations about class docstring and class constructor
DOC4xx: Violations about “yield” statements
DOC5xx: Violations about “raise” statements
DOC6xx: Violations about class attributes
```

**Comment by adamamer20** [comment]
Yes that's exactly what I was considering. Very good, they also have a pre-commit hook:
```- repo: https://github.com/jsh9/pydoclint
  rev: <latest_tag>
  hooks:
    - id: pydoclint
      args: [--style=google, --check-return-types=False]
```
